Repository codestates-seb/seb40_main_019, pull requests merged in 2022-11, with the labels that each got.

#2 [FE] Feat: 초기 레이아웃 설정
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/scss/common.scss
  client/src/components/footer/css/footer.scss
  client/src/components/footer/js/Footer.js
  client/src/components/header/css/header.scss
  client/src/components/header/css/nav.scss
  client/src/components/header/js/Header.js
  client/src/components/header/js/Nav.js
  client/src/components/home/css/home.scss
  client/src/components/home/js/Home.js
  client/src/components/layout/css/layout.scss
  client/src/components/layout/js/Layout.js
  client/src/components/main/css/main.scss
  client/src/components/main/js/Main.js
  client/src/index.js
  client/src/redux/store.js
Labels: 클라이언트

#8 Feat: aws 파이프라인 스크립트, 설정 추가 #7
  backend/appspec.yml
  backend/scripts/initialize.sh
  backend/scripts/server_clear.sh
  backend/scripts/server_start.sh
  backend/scripts/server_stop.sh
  buildspec.yml
Labels: 백엔드

#9 [BE] Fix: buildspec 수정
  backend/buildspec.yml
Labels: 백엔드, 핫픽스

#20 Refactor: 도메인 구조 변경
  backend/src/main/java/com/backend/domain/answer/api/AnswerController.java
  backend/src/main/java/com/backend/domain/answer/application/AnswerService.java
  backend/src/main/java/com/backend/domain/answer/dao/AnswerRepository.java
  backend/src/main/java/com/backend/domain/answer/domain/Answer.java
  backend/src/main/java/com/backend/domain/answer/dto/AnswerPostDto.java
  backend/src/main/java/com/backend/domain/answer/dto/AnswerResponseDto.java
  backend/src/main/java/com/backend/domain/comment/api/CommentController.java
  backend/src/main/java/com/backend/domain/comment/application/CommentService.java
  backend/src/main/java/com/backend/domain/comment/dao/CommentRepository.java
  backend/src/main/java/com/backend/domain/comment/domain/Comment.java
  backend/src/main/java/com/backend/domain/comment/domain/CommentLike.java
  backend/src/main/java/com/backend/domain/comment/dto/CommentPostDto.java
  backend/src/main/java/com/backend/domain/comment/dto/CommentResponseDto.java
  backend/src/main/java/com/backend/domain/community/api/CommunityController.java
  backend/src/main/java/com/backend/domain/community/application/Community.java
  backend/src/main/java/com/backend/domain/community/dao/CommunityRepository.java
  backend/src/main/java/com/backend/domain/community/domain/Community.java
  backend/src/main/java/com/backend/domain/community/domain/CommunityCategory.java
  backend/src/main/java/com/backend/domain/community/domain/PostLike.java
  backend/src/main/java/com/backend/domain/community/dto/CommunityPostDto.java
  backend/src/main/java/com/backend/domain/community/dto/CommunityResponseDto.java
  backend/src/main/java/com/backend/domain/order/domain/OrderStatus.java
  backend/src/main/java/com/backend/domain/product/domain/Product.java
  backend/src/main/java/com/backend/domain/question/api/QuestionController.java
  backend/src/main/java/com/backend/domain/question/application/QuestionService.java
  backend/src/main/java/com/backend/domain/question/dao/QuestionRepository.java
  backend/src/main/java/com/backend/domain/question/domain/Question.java
  backend/src/main/java/com/backend/domain/question/dto/QuestionPostDto.java
  backend/src/main/java/com/backend/domain/question/dto/QuestionResponseDto.java
  backend/src/main/java/com/backend/domain/review/domain/Review.java
  backend/src/main/java/com/backend/domain/review/domain/ReviewStar.java
  backend/src/main/java/com/backend/domain/user/domain/User.java
Labels: 백엔드, 리팩토링

#32 [BE] Feat/회원가입 구현
  backend/build.gradle
  backend/src/main/java/com/backend/domain/refreshToken/api/UserController.java
  backend/src/main/java/com/backend/domain/refreshToken/application/UserService.java
  backend/src/main/java/com/backend/domain/refreshToken/dao/RefreshTokenRepository.java
  backend/src/main/java/com/backend/domain/refreshToken/dao/UserRepository.java
  backend/src/main/java/com/backend/domain/refreshToken/domain/RefreshToken.java
  backend/src/main/java/com/backend/domain/refreshToken/domain/User.java
  backend/src/main/java/com/backend/domain/refreshToken/dto/UserPostDto.java
  backend/src/main/java/com/backend/domain/refreshToken/dto/UserResponseDto.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenEmpty.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenExpired.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenInvalid.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenMalformed.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenNotFound.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenSignatureInvalid.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenUnsupported.java
  backend/src/main/java/com/backend/domain/user/api/AuthController.java
  backend/src/main/java/com/backend/domain/user/api/UserController.java
  backend/src/main/java/com/backend/domain/user/application/AuthService.java
  backend/src/main/java/com/backend/domain/user/application/CustomUserDetailsService.java
  backend/src/main/java/com/backend/domain/user/application/UserService.java
  backend/src/main/java/com/backend/domain/user/dao/UserRepository.java
  backend/src/main/java/com/backend/domain/user/domain/Address.java
  backend/src/main/java/com/backend/domain/user/domain/AuthUser.java
  backend/src/main/java/com/backend/domain/user/domain/User.java
  backend/src/main/java/com/backend/domain/user/domain/UserRole.java
  backend/src/main/java/com/backend/domain/user/dto/ReissueResponseDto.java
  backend/src/main/java/com/backend/domain/user/dto/SignUpRequestDto.java
  backend/src/main/java/com/backend/domain/user/dto/TokenDto.java
  backend/src/main/java/com/backend/domain/user/dto/UserPatchDto.java
  backend/src/main/java/com/backend/domain/user/dto/UserPostDto.java
  backend/src/main/java/com/backend/domain/user/dto/UserResponseDto.java
  backend/src/main/java/com/backend/domain/user/exception/EmailDuplication.java
  backend/src/main/java/com/backend/domain/user/exception/MemberNotFound.java
  backend/src/main/java/com/backend/domain/user/exception/NotLoginMember.java
  backend/src/main/java/com/backend/domain/user/exception/UserNameDuplication.java
  backend/src/main/java/com/backend/global/annotation/CurrentMember.java
  backend/src/main/java/com/backend/global/config/error/BusinessLogicException.java
  backend/src/main/java/com/backend/global/config/error/ErrorResponse.java
  backend/src/main/java/com/backend/global/config/error/ExceptionCode.java
  backend/src/main/java/com/backend/global/config/security/SecurityConfig.java
  backend/src/main/java/com/backend/global/config/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/backend/global/config/security/filter/JwtVerificationFilter.java
  backend/src/main/java/com/backend/global/config/security/handler/UserAuthenticationSuccessHandler.java
  backend/src/main/java/com/backend/global/jwt/JwtAccessDeniedHandler.java
  backend/src/main/java/com/backend/global/jwt/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/backend/global/jwt/JwtSecurityConfig.java
  backend/src/main/java/com/backend/global/jwt/TokenProvider.java
Labels: 백엔드, 기능

#33 [BE] Feat/로그인
  backend/build.gradle
  backend/src/main/java/com/backend/domain/user/domain/AuthUser.java
  backend/src/main/java/com/backend/global/config/error/ExceptionCode.java
  backend/src/main/java/com/backend/global/config/error/GlobalExceptionHandler.java
  backend/src/main/java/com/backend/global/config/security/SecurityConfig.java
  backend/src/main/java/com/backend/global/config/security/exception/InvalidJwtTokenException.java
  backend/src/main/java/com/backend/global/config/security/exception/JwtExceptionFilter.java
  backend/src/main/java/com/backend/global/config/security/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/backend/global/config/security/handler/UserAuthenticationFailureHandler.java
  backend/src/main/java/com/backend/global/config/security/handler/UserAuthenticationSuccessHandler.java
  backend/src/main/java/com/backend/global/jwt/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/backend/global/jwt/TokenProvider.java
Labels: 백엔드, 기능

#30 Feat/22 상품리스트
  client/src/App.js
  client/src/pages/Products/css/products.scss
  client/src/pages/Products/js/Products.js
Labels: 클라이언트, 기능

#34 [FE] Feat/27 fe 회원가입
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.scss
  client/src/assets/img/logo_blue.png
  client/src/components/layout/css/layout.scss
  client/src/components/main/css/main.scss
  client/src/components/sign/css/formButtonBlue.scss
  client/src/components/sign/css/formButtonYellow.scss
  client/src/components/sign/css/formDisabledInput.scss
  client/src/components/sign/css/formInput.scss
  client/src/components/sign/css/formInputError.scss
  client/src/components/sign/js/FormButtonBlue.js
  client/src/components/sign/js/FormButtonYellow.js
  client/src/components/sign/js/FormDisabledInput.js
  client/src/components/sign/js/FormInput.js
  client/src/components/sign/js/FormInputError.js
  client/src/components/signup/css/signupForm.scss
  client/src/components/signup/css/signupModal.scss
  client/src/components/signup/js/SignupForm.js
  client/src/components/signup/js/SignupModal.js
  client/src/index.js
  client/src/pages/home/js/Home.js
  client/src/pages/login/css/login.scss
  client/src/pages/login/js/Login.js
  client/src/pages/signup/css/signup.scss
  client/src/pages/signup/js/Signup.js
  client/src/redux/reducers/signupModal.js
  client/src/redux/store.js
  client/src/util/api/signupForm.js
Labels: 클라이언트, 기능

#36 [BE] AWS Parameter Store 설정
  backend/build.gradle
  backend/src/main/java/com/backend/BackendApplication.java
  backend/src/main/resources/application-server.yml
  backend/src/main/resources/application.yml
Labels: 백엔드, 기능

#37 [BE] Refactor: parameter store 수정
  backend/src/main/java/com/backend/BackendApplication.java
Labels: 백엔드, 리팩토링

#38 Feat/22 상품리스트
  client/.eslintrc.json
  client/data/data.json
  client/data/db.json
  client/db.json
  client/package-lock.json
  client/package.json
  client/src/components/productItem/ProductItem.js
  client/src/components/productItem/productItem.scss
  client/src/pages/Products/css/products.scss
  client/src/pages/Products/js/Products.js
  package-lock.json
Labels: 클라이언트, 기능

#40 [BE] Feat/이메일인증
  backend/build.gradle
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenEmpty.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenExpired.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenInvalid.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenMalformed.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenNotFound.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenSignatureInvalid.java
  backend/src/main/java/com/backend/domain/refreshToken/exception/TokenUnsupported.java
  backend/src/main/java/com/backend/domain/user/api/SendMail.java
  backend/src/main/java/com/backend/domain/user/application/RegisterMail.java
  backend/src/main/java/com/backend/domain/user/exception/EmailDuplication.java
  backend/src/main/java/com/backend/domain/user/exception/MemberNotFound.java
  backend/src/main/java/com/backend/domain/user/exception/NotLoginMember.java
  backend/src/main/java/com/backend/domain/user/exception/UserNameDuplication.java
  backend/src/main/java/com/backend/global/config/MailConfig.java
  backend/src/main/java/com/backend/global/config/security/filter/JwtVerificationFilter.java
  backend/src/main/java/com/backend/global/config/security/handler/UserAuthenticationFailureHandler.java
  backend/src/main/java/com/backend/global/error/BusinessLogicException.java
  backend/src/main/java/com/backend/global/error/ErrorResponse.java
  backend/src/main/java/com/backend/global/error/ExceptionCode.java
  backend/src/main/java/com/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/com/backend/global/jwt/TokenProvider.java
  backend/src/main/java/com/backend/global/jwt/exception/InvalidJwtTokenException.java
  backend/src/main/java/com/backend/global/jwt/exception/JwtExceptionFilter.java
  backend/src/main/resources/application.yml
Labels: 백엔드, 기능

#42 [FE] Feat/27 fe 회원가입
  client/.env.example
  client/.eslintrc.json
  client/package-lock.json
  client/src/assets/img/googleIcon.png
  client/src/assets/img/kakaoIcon.png
  client/src/components/sign/css/formInputError.scss
  client/src/components/signin/css/signinForm.scss
  client/src/components/signin/js/SigninForm.js
  client/src/components/signup/js/SignupForm.js
  client/src/components/signup/js/SignupModal.js
  client/src/pages/login/css/login.scss
  client/src/pages/login/js/Login.js
  client/src/redux/reducers/signupModalSlice.js
  client/src/redux/store.js
  client/src/util/api/signupForm.js
Labels: 클라이언트, 기능

#47 products 전체 페이지 레이아웃
  client/package-lock.json
  client/src/App.js
  client/src/components/productItem/css/productItem.scss
  client/src/components/productItem/css/productItems.scss
  client/src/components/productItem/js/ProductItem.js
  client/src/components/productItem/js/ProductItems.js
  client/src/components/sidebar/css/sidebar.scss
  client/src/pages/shopProductList/css/shopProductList.scss
  client/src/pages/shopProductList/js/ShopProductList.js
Labels: 클라이언트, 리팩토링

#48 Feat: 관리자 테스트 계정 생성 추가, 엔드포인트 수정
  backend/src/main/java/com/backend/domain/user/api/AuthController.java
  backend/src/main/java/com/backend/domain/user/application/AuthService.java
Labels: 백엔드, 기능

#54 Refactor: 테스트계정 생성 로직 수정
  backend/src/main/java/com/backend/domain/user/application/AuthService.java
Labels: 백엔드, 리팩토링

#64 Feat/22 상품리스트
  client/src/components/shop/css/productDetailBox.scss
  client/src/components/shop/css/productInfo.scss
  client/src/components/shop/js/ProductInfo.js
  client/src/pages/shopProductDetail/css/shopProductDetail.scss
  client/src/pages/shopProductDetail/js/ShopProductDetail.js
Labels: 클라이언트, 리팩토링

#68 [FE] Feat/65 fe 결제
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/signin/js/SigninForm.js
  client/src/pages/payment/js/Failed.js
  client/src/pages/payment/js/Success.js
  client/src/util/api/payment.js
Labels: 클라이언트, 기능

#70 Fix: 레이아웃 컴포넌트 수정, products 컴포넌트 수정
  client/src/components/footer/css/footer.scss
  client/src/components/header/css/nav.scss
  client/src/components/layout/css/layout.scss
  client/src/components/layout/css/shopLayout.scss
  client/src/components/layout/js/Layout.js
  client/src/components/layout/js/ShopLayout.js
  client/src/components/main/css/main.scss
  client/src/components/main/js/Main.js
  client/src/components/productItem/css/productItem.scss
  client/src/components/productItem/css/productItems.scss
  client/src/components/sidebar/css/sidebar.scss
  client/src/components/sidebar/css/sidebarMenu.scss
  client/src/components/sidebar/js/Sidebar.js
  client/src/pages/shopProductList/css/shopProductList.scss
  client/src/pages/shopProductList/js/ShopProductList.js
Labels: 클라이언트, 리팩토링

#74 필터링 추가
  client/src/components/productItem/css/productItems.scss
  client/src/components/productItem/js/ProductItems.js
Labels: 클라이언트, 기능

#87 [FE] Feat/85 fe 마이페이지유저
  client/src/App.js
  client/src/components/footer/css/footer.scss
  client/src/components/main/css/main.scss
  client/src/components/mypage/css/userInfo.scss
  client/src/components/mypage/js/UserInfo.js
  client/src/components/mypage/mypagePoint/css/mypagePoint.scss
  client/src/components/mypage/mypagePoint/js/MypagePoint.js
  client/src/components/mypage/mypageUser/css/mypageUser.scss
  client/src/components/mypage/mypageUser/js/MypageUser.js
  client/src/components/mypage/mypageUserEdit/css/mypageUserEdit.scss
  client/src/components/mypage/mypageUserEdit/js/MypageUserEdit.js
  client/src/pages/mypage/point/css/mypagePointPage.scss
  client/src/pages/mypage/point/js/MypagePointPage.js
  client/src/pages/mypage/user/css/mypageUserPage.scss
  client/src/pages/mypage/user/js/MypageUserPage.js
  client/src/pages/mypage/userEdit/css/mypageUserEditPage.scss
  client/src/pages/mypage/userEdit/js/MypageUserEditPage.js
  client/src/pages/oauth/OauthGoogle.js
  client/src/util/api/mypageUser.js
  client/src/util/api/oauthKakao.js
Labels: 클라이언트, 기능

#88 Feat/77 상품 장바구니&결제
  client/src/components/shop/css/productInfoBox.scss
  client/src/components/shop/js/ProductInfoBox.js
  client/src/components/shop/productOrder/css/orderSummary.scss
  client/src/components/shop/productOrder/js/CartList.js
  client/src/components/shop/productOrder/js/OrderSummary.js
  client/src/pages/shopProductDetail/css/shopProductDetail.scss
  client/src/pages/shopProductOrder/css/shopProductOrder.scss
  client/src/pages/shopProductOrder/js/ShopProductOrder.js
Labels: 클라이언트

#95 Feat/77 상품 장바구니&결제
  client/data/data.json
  client/src/components/shop/productOrder/css/cartList.scss
  client/src/components/shop/productOrder/css/cartListItem.scss
  client/src/components/shop/productOrder/css/orderSummary.scss
  client/src/components/shop/productOrder/js/CartList.js
  client/src/components/shop/productOrder/js/CartListItem.js
  client/src/components/shop/productOrder/js/OrderSummary.js
  client/src/pages/shopProductOrder/css/shopProductOrder.scss
  client/src/pages/shopProductOrder/js/ShopProductOrder.js
Labels: 클라이언트, 기능

#96 [FE] Feat: 유저정보 수정 추가
  client/src/components/mypage/css/userInfo.scss
  client/src/components/mypage/js/UserInfo.js
  client/src/components/mypage/mypageUser/js/MypageUser.js
  client/src/components/mypage/mypageUserEdit/css/mypageUserEdit.scss
  client/src/components/mypage/mypageUserEdit/js/MypageUserEdit.js
  client/src/util/api/mypageUser.js
Labels: 클라이언트, 기능

#97 [FE] Feat/61 fe 소셜로그인
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/signin/js/SigninForm.js
  client/src/index.js
  client/src/pages/oauth/OauthGoogle.js
  client/src/pages/oauth/OauthKakao.js
  client/src/redux/reducers/userSlice.js
  client/src/util/api/loginForm.js
  client/src/util/api/oauthGoogle.js
  client/src/util/api/oauthKakao.js
  client/src/util/cookie/cookie.js
Labels: 클라이언트, 기능

#103 [FE] Feat: 로그인, 로그아웃, 엑세스 토큰 재발급 로직 변경
  client/src/App.js
  client/src/util/api/Reissue.js
  client/src/util/api/loginForm.js
  client/src/util/api/mypageUser.js
Labels: 클라이언트, 기능

#104 [FE] Feat: 새 비밀번호 확인 정규표현식 변경
  client/src/util/api/mypageUser.js
Labels: 클라이언트, 기능

#110 [BE] 로그아웃, 재발급, 유저정보 수정 구현
  backend/scripts/server_sttop.sh
  backend/src/main/java/com/backend/domain/review/application/ReviewService.java
  backend/src/main/java/com/backend/domain/user/api/UserController.java
  backend/src/main/java/com/backend/domain/user/application/UserService.java
  backend/src/main/java/com/backend/domain/user/dao/UserRepository.java
  backend/src/main/java/com/backend/domain/user/domain/Address.java
  backend/src/main/java/com/backend/domain/user/domain/User.java
  backend/src/main/java/com/backend/domain/user/dto/UserLoginResponseDto.java
  backend/src/main/java/com/backend/domain/user/dto/UserPatchDto.java
  backend/src/main/java/com/backend/domain/user/dto/UserPostDto.java
  backend/src/main/java/com/backend/domain/user/dto/UserResponseDto.java
  backend/src/main/java/com/backend/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/backend/global/config/SecurityConfig.java
  backend/src/main/java/com/backend/global/config/auth/dto/OAuthAttributes.java
  backend/src/main/java/com/backend/global/config/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/backend/global/config/auth/handler/CustomOAuth2UserService.java
  backend/src/main/java/com/backend/global/config/auth/handler/OAuth2userSuccessHandler.java
  backend/src/main/java/com/backend/global/error/ExceptionCode.java
  backend/src/main/resources/application-server.yml
  backend/src/main/resources/application.yml
Labels: 백엔드, 기능

#112 [FE] Feat: 로그인, 로그아웃, 토큰 재발급 구현
  client/src/App.js
  client/src/App.scss
  client/src/components/mypage/mypagePoint/css/mypagePoint.scss
  client/src/components/mypage/mypagePoint/js/MypagePoint.js
  client/src/components/signup/js/SignupForm.js
  client/src/components/signup/js/SignupModal.js
  client/src/pages/oauth/OauthKakao.js
  client/src/redux/reducers/loginSlice.js
  client/src/redux/reducers/signupModalSlice.js
  client/src/util/api/Reissue.js
  client/src/util/api/loginForm.js
  client/src/util/api/oauthGoogle.js
  client/src/util/api/oauthKakao.js
Labels: 클라이언트, 기능

#122 [FE] Feat/61 fe 소셜로그인
  client/src/pages/oauth/OauthGoogle.js
  client/src/util/api/oauthGoogle.js
  client/src/util/api/oauthKakao.js
Labels: 클라이언트, 기능

#125 Refactor/123 fe 회원가입
  client/src/components/signup/js/SignupForm.js
  client/src/components/signup/js/SignupModal.js
  client/src/redux/reducers/signupModalSlice.js
  client/src/redux/reducers/userSlice.js
  client/src/util/api/loginForm.js
Labels: 클라이언트, 리팩토링

#138 [FE] Feat/105 fe 포인트조회
  client/src/App.js
  client/src/util/api/mypageUser.js
  client/src/util/api/payment.js
  client/src/util/api/point.js
Labels: 클라이언트, 기능

#141 [FE] Feat: 회원 정보 조회, 수정, 삭제 구현
  client/src/App.js
  client/src/components/mypage/mypageUser/js/MypageUser.js
  client/src/components/mypage/mypageUserEdit/js/MypageUserEdit.js
  client/src/util/api/mypageUser.js
Labels: 클라이언트, 기능

#149 [FE] Feat: 포인트 결제, 충전, 조회 구현
  client/.env.example
  client/src/App.js
  client/src/components/mypage/mypagePoint/css/mypagePointButton.scss
  client/src/components/mypage/mypagePoint/js/MypagePointButton.js
  client/src/components/signin/js/SigninForm.js
  client/src/pages/payment/js/Success.js
  client/src/util/api/loginForm.js
  client/src/util/api/payment.js
  client/src/util/api/point.js
Labels: 클라이언트, 기능

#152 [FE] Refactor/123 fe 회원가입
  client/src/components/signup/js/SignupForm.js
  client/src/components/signup/js/SignupModal.js
Labels: 클라이언트, 리팩토링

#154 [FE] Refactor/124 fe 로그인
  client/src/components/signin/js/SigninForm.js
  client/src/util/api/loginForm.js
  client/src/util/api/oauthGoogle.js
  client/src/util/api/oauthKakao.js
Labels: 클라이언트, 리팩토링

#155 Refactor: 게스트 계정 비밀번호 변경 차단
  client/src/components/mypage/mypageUserEdit/js/MypageUserEdit.js
Labels: 클라이언트, 리팩토링

#156 [FE] Feat: 회원 탈퇴 확인 과정 추가
  client/src/components/mypage/mypageUser/css/deleteUserModal.scss
  client/src/components/mypage/mypageUser/js/DeleteUserModal.js
  client/src/components/mypage/mypageUser/js/MypageUser.js
  client/src/util/api/mypageUser.js
Labels: 클라이언트, 기능

#158 [FE] Feat: 아이디 찾기 임시 구현
  client/src/components/signin/css/findEmailModal.scss
  client/src/components/signin/css/findPasswordModal.scss
  client/src/components/signin/css/signinForm.scss
  client/src/components/signin/js/FindEmailModal.js
  client/src/components/signin/js/FindPasswordModal.js
  client/src/components/signin/js/SigninForm.js
  client/src/util/api/userAccount.js
Labels: 클라이언트, 기능

#160 [FE] Feat: 비밀번호 찾기 임시 구현
  client/src/components/signin/css/findPasswordModal.scss
  client/src/components/signin/js/FindEmailModal.js
  client/src/components/signin/js/FindPasswordModal.js
  client/src/util/api/userAccount.js
Labels: 클라이언트, 기능

#162 [FE] Feat: 장바구니 담기 구현
  client/src/components/shop/js/BuyAddBtn.js
  client/src/components/shop/js/ProductInfoBox.js
  client/src/pages/shopProductDetail/js/ShopProductDetail.js
Labels: 클라이언트, 기능

#169 [FE]Feat: 아이디 찾기 구현
  client/src/util/api/userAccount.js
Labels: 클라이언트, 기능

#170 [FE] Feat: 비밀번호 찾기 구현
  client/src/components/signin/js/FindPasswordModal.js
  client/src/util/api/userAccount.js
Labels: 클라이언트, 기능

#172 Feat: 테스트계정 삭제 스케줄러 구현
  backend/src/main/java/com/backend/domain/point/domain/Point.java
  backend/src/main/java/com/backend/domain/user/api/UserController.java
  backend/src/main/java/com/backend/domain/user/application/UserService.java
  backend/src/main/java/com/backend/domain/user/dao/UserRepository.java
  backend/src/main/java/com/backend/domain/user/domain/User.java
  backend/src/main/java/com/backend/global/utils/ScheduleTasks.java
Labels: 백엔드, 기능

#175 Feat: RefreshToken 삭제 스케줄러
  backend/src/main/java/com/backend/domain/refreshToken/application/RefreshTokenService.java
  backend/src/main/java/com/backend/domain/refreshToken/dao/RefreshTokenRepository.java
  backend/src/main/java/com/backend/domain/refreshToken/domain/RefreshToken.java
  backend/src/main/java/com/backend/domain/user/api/MailController.java
  backend/src/main/java/com/backend/domain/user/application/UserService.java
  backend/src/main/java/com/backend/global/config/auth/filter/JwtAuthenticationFilter.java
  backend/src/main/java/com/backend/global/config/auth/handler/OAuth2userSuccessHandler.java
  backend/src/main/java/com/backend/global/utils/ScheduleTasks.java
  backend/src/main/java/com/backend/global/utils/jwt/JwtTokenizer.java
Labels: 백엔드, 기능

#178 [FE] Feat/163 fe 장바구니
  client/src/components/shop/js/BuyAddBtn.js
  client/src/components/shop/js/ProductInfoSmall.js
  client/src/components/shop/productOrder/css/cartListItem.scss
  client/src/components/shop/productOrder/css/cartQuantityBtn.scss
  client/src/components/shop/productOrder/js/CartList.js
  client/src/components/shop/productOrder/js/CartListItem.js
  client/src/components/shop/productOrder/js/CartQuantityBtn.js
  client/src/components/shop/productOrder/js/OrderSummary.js
  client/src/pages/shopProductDetail/js/ShopProductDetail.js
  client/src/pages/shopProductOrder/css/shopProductOrder.scss
  client/src/pages/shopProductOrder/js/OrderMobileButton.js
  client/src/pages/shopProductOrder/js/ShopProductOrder.js
Labels: 클라이언트, 기능

#185 [FE] Feat/163 fe 장바구니
  client/src/components/payment/css/paymentModal.scss
  client/src/components/payment/js/PaymentModal.js
  client/src/components/shop/js/BuyAddBtn.js
  client/src/components/shop/js/ProductInfoBox.js
  client/src/components/shop/js/ProductInfoSmall.js
  client/src/components/shop/productOrder/css/orderSummary.scss
  client/src/components/shop/productOrder/js/OrderSummary.js
  client/src/components/sign/css/formButtonBlue.scss
  client/src/components/sign/css/formDisabledInput.scss
  client/src/components/sign/js/FormDisabledInput.js
  client/src/pages/shopProductDetail/js/ShopProductDetail.js
  client/src/pages/shopProductOrder/js/OrderMobileButton.js
  client/src/pages/shopProductOrder/js/ShopProductOrder.js
Labels: 클라이언트, 기능

#186 [FE]Fix: merge 에러 수정
  client/src/components/shop/productOrder/js/OrderSummary.js
Labels: 클라이언트, 버그

#188 [FE] Feat: 단품 주문, 결제 구현
  client/src/components/payment/js/PaymentModal.js
  client/src/util/api/order.js
Labels: 클라이언트, 기능

#189 [BE] Fix: PointHistory getList 페이지네이션 수정
  backend/src/main/java/com/backend/domain/point/api/PointController.java
Labels: 백엔드, 버그

#190 Fix: 포인트 내역 조회 페이지네이션 오류 수정
  backend/src/main/java/com/backend/domain/point/api/PointController.java
  backend/src/main/java/com/backend/domain/point/application/PointService.java
  backend/src/main/java/com/backend/global/dto/request/PageInfo.java
Labels: 백엔드, 버그

#192 [FE] Feat: 결제 연동 준비
  client/src/components/mypage/mypagePoint/js/MypagePointList.js
  client/src/pages/mypage/point/css/mypagePointPage.scss
  client/src/pages/mypage/point/js/MypagePointPage.js
  client/src/util/api/point.js
Labels: 클라이언트, 기능

#194 [FE] Feat: 로딩 컴포넌트 구현
  client/src/assets/img/Spinner-1s-200px.gif
  client/src/components/loading/css/loading.scss
  client/src/components/loading/js/Loading.js
  client/src/components/main/css/main.scss
  client/src/pages/payment/css/failed.scss
  client/src/pages/payment/css/success.scss
  client/src/pages/payment/js/Failed.js
  client/src/pages/payment/js/Success.js
Labels: 클라이언트, 기능

#198 [FE] Feat: 소셜 로그인 스피너 적용
  client/src/App.js
  client/src/pages/oauth/css/oauthGoogle.scss
  client/src/pages/oauth/css/oauthKakao.scss
  client/src/pages/oauth/js/OauthGoogle.js
  client/src/pages/oauth/js/OauthKakao.js
  client/src/util/api/userAccount.js
Labels: 클라이언트, 기능

#200 [BE] Feat/서버 시간대 변경
  backend/src/main/java/com/backend/global/config/TimeZoneConfig.java
Labels: 백엔드, 기능

#203 [FE] Feat: 결제 연동
  client/src/pages/payment/js/Success.js
  client/src/util/api/payment.js
Labels: 클라이언트, 기능

#204 Feat/177 fe ai컴포넌트
  client/src/components/productItem/css/aiComponent.scss
  client/src/components/productItem/css/productItems.scss
  client/src/components/productItem/js/AiComponent.js
Labels: 클라이언트, 기능

#206 [FE] Feat: 포인트 히스토리 구현
  client/src/components/mypage/mypagePoint/js/MypagePointList.js
  client/src/components/mypage/mypagePoint/js/MypagePointListItem.js
  client/src/pages/shopMypageOrderList/js/ShopMypageOrderList.js
Labels: 클라이언트, 기능

#211 [FE] Fix: 상품 리스트 페이지 디자인 버그 수정
  client/src/components/productItem/css/aiComponent.scss
  client/src/components/productItem/css/productItem.scss
  client/src/components/productItem/css/productItems.scss
  client/src/components/productItem/js/ProductItem.js
Labels: 클라이언트, 버그

#212 [FE] Fix: 상품 디테일 페이지 디자인 수정
  client/src/components/productItem/css/aiComponent.scss
  client/src/components/productItem/css/productItem.scss
  client/src/components/productItem/js/AiComponent.js
  client/src/components/shop/css/productInfoBox.scss
  client/src/components/shop/productOrder/css/cartList.scss
Labels: 클라이언트, 버그

#213 Fix: 소셜로그인마다 포인트 충전되는 버그 수정
  backend/src/main/java/com/backend/global/config/auth/dto/OAuthAttributes.java
  backend/src/main/java/com/backend/global/config/auth/handler/CustomOAuth2UserService.java
Labels: 백엔드, 버그

#214 [FE] Fix/197 fe 버그수정
  client/src/components/payment/js/PaymentModal.js
  client/src/components/productItem/css/aiComponent.scss
  client/src/components/shop/js/BuyAddBtn.js
  client/src/components/shop/js/ProductInfoBox.js
  client/src/components/shop/js/ProductInfoSmall.js
  client/src/components/shop/productOrder/js/OrderSummary.js
  client/src/pages/shopProductDetail/js/ShopProductDetail.js
  client/src/pages/shopProductOrder/js/OrderMobileButton.js
Labels: 클라이언트, 버그

#216 반응형 재구현, input숫자만 입력하도록 설정함
  client/src/components/productItem/css/aiComponent.scss
  client/src/components/productItem/js/AiComponent.js
Labels: 클라이언트, 기능, 리팩토링

#217 [FE] Fix: useFetch setTimeout 제거
  client/src/util/api/point.js
  client/src/util/useFetch.js
Labels: 클라이언트, 버그

#219 [FE] Fix: 결제 정보 유효성 검사 추가
  client/src/components/payment/js/PaymentModal.js
  client/src/components/shop/js/BuyAddBtn.js
  client/src/components/shop/js/ProductInfoSmall.js
  client/src/components/shop/productOrder/js/CartList.js
  client/src/components/shop/productOrder/js/CartListItem.js
  client/src/pages/shopMypageOrderList/js/ShopMypageOrderList.js
  client/src/pages/shopProductOrder/js/ShopProductOrder.js
  client/src/util/api/order.js
Labels: 클라이언트, 버그

#220 [FE] Fix: 선택한 상품 없이 구매 차단
  client/src/components/shop/productOrder/css/cartList.scss
  client/src/components/shop/productOrder/js/OrderSummary.js
  client/src/pages/shopProductOrder/js/OrderMobileButton.js
Labels: 클라이언트, 버그
